#!/bin/bash

VERSION='0.18.24.8-beta'

# Docker image config
NAME='crawler-modis'

# Local variables
DOWNLOAD_DIR='/Users/javerdejo/Desktop/ecosur/eris/modis-crawler/run/downloads/'
LOGFILE='/Users/javerdejo/Desktop/ecosur/eris/modis-crawler/run/log/'
